version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: tuu-capricho-db
    env_file:
      - ./.env # Carga variables desde el archivo .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tuu-capricho-server
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./pdfs:/usr/src/app/pdfs:ro # Monta la carpeta de PDFs (solo lectura)
    depends_on:
      db:
        condition: service_healthy # Espera a que la DB esté saludable

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tuu-capricho-client
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres-data: